# Generated by Django 3.2.14 on 2022-09-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HL',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your HLs'),
        ),
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role: Teacher, Student11, or Student12?'),
        ),
        migrations.AddField(
            model_name='user',
            name='SL',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your SLs'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=255, verbose_name='Be sure to include You HLs and SLs'),
        ),
    ]
