# Generated by Django 3.2.14 on 2022-09-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220915_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role: teacher, student_11, or student_12?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=255, verbose_name='A quick description of who you are.'),
        ),
    ]
